# OA: (0)Dye, Circuits, Plastic, Hamburger, (4)Filament, 
# Patch, Dumbbells, Charcoal, Feather, (9)Resin, Shard, 
# Tough Stuff, Iron Filament, Polish, (14)Ectoplasm, Pebble, Perfection,
# Poison, Ash, (19)New Tag, Vibrations, Water, Goo, Rubber, (24)Dust, 
# Ice, Crystalline Shard, Strange Capacitor, Glint, (29)Cellulose, 
# Magma Ball, Ghastly Eye, Jotunn Shard

# Unreal Chance: 1/858k
# Divslat Chance: 1/2250
# Exotic Chance: 1/100k
mat_called_name = [
    "painted",
    "electronic",
    "plastic",
    "edible",
    "emitslight",
    "madewithfabric",
    "heavy",
    "dull",
    "light",
    "organic",
    "glass",
    "hard",
    "magnetic",
    "shiny",
    "haunted",
    "stony",
    "pure",
    "poisonous",
    "hot",
    "fresh",
    "makesnoise",
    "wet",
    "slimy",
    "bouncy",
    "ancient",
    "cold",
    "glass",
    "electronic",
    "shiny",
    "plastic",
    "hot",
    "haunted",
    "cold"
]

mat_display_name = [
    "Dyes",
    "Circuits",
    "Plastics",
    "Hamburgers",
    "Filaments",
    "Patches",
    "Dumbbells",
    "Charcoal",
    "Feathers",
    "Resin",
    "Shards",
    "Tough Stuff",
    "Iron Filaments",
    "Polish",
    "Ectoplasm",
    "Pebbles",
    "Perfections",
    "Poison",
    "Ash",
    "New Tags",
    "Vibrations",
    "Water",
    "Goo",
    "Rubber",
    "Dust",
    "Ice",
    "Crystalline Shards",
    "Strange Capacitors",
    "Glint",
    "Cellulose",
    "Magma Balls",
    "Ghastly Eyes",
    "Jotuun Shards"
]